### Get home page
GET http://localhost:8081/api/page/home

### Get category page
GET http://localhost:8081/api/page/category?name=hoa-tuoi

### Get navigate
GET http://localhost:8081/api/page/navigate